"use client";
import { useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Pencil, Plus, Search, SlidersHorizontal } from "lucide-react";
import { DIFFICULTIES, OUTCOMES, Problem, latestReflection, visibleProblems, shortDate } from "@/lib/model";
import { useWorkspace } from "./provider";
import { AddProblem } from "./problem-form";
import { EmptyState, Modal, OutcomeLabel, PageHeader, ProblemLink, Tags } from "./ui";

export function Problems() {
  const {data,setAddOpen,startSession}=useWorkspace();
  const [query,setQuery]=useState("");
  const [topic,setTopic]=useState("");
  const [outcome,setOutcome]=useState("");
  const [selected,setSelected]=useState<Problem|null>(null);
  const [editing,setEditing]=useState<Problem|null>(null);
  const available=visibleProblems(data);
  const topics=[...new Set(available.flatMap(p=>p.tags))].sort();
  const filtered=available.filter(p=>[p.title,p.problemCode,p.platform,...p.tags].join(" ").toLowerCase().includes(query.toLowerCase()) && (!topic||p.tags.includes(topic)) && (!outcome||(latestReflection(data,p.id)?.outcome??"fresh")===outcome));
  function clear(){setQuery("");setTopic("");setOutcome("");}
  return <div className="page-enter"><PageHeader eyebrow="THE PRACTICE NOTEBOOK" title="Problems worth your time." description="A collection of things to understand, one attempt at a time." action={<button className="button primary" onClick={()=>setAddOpen(true)}><Plus size={17}/>Add problem</button>}/>
    <div className="collection-intro"><span><strong className="mono">{String(available.length).padStart(2,"0")}</strong> problems in your collection</span><span className="muted small">Every attempt has a place here.</span></div>
    <div className="filter-bar"><label className="search-field"><Search size={18}/><span className="sr-only">Search problems</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a problem, topic, or ID…"/></label><div className="filter-select"><SlidersHorizontal size={16}/><label className="sr-only" htmlFor="topic-filter">Filter by topic</label><select id="topic-filter" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{topics.map(t=><option key={t}>{t}</option>)}</select></div><div className="filter-select"><label className="sr-only" htmlFor="outcome-filter">Filter by outcome</label><select id="outcome-filter" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">All outcomes</option><option value="fresh">Not attempted</option>{Object.entries(OUTCOMES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div></div>
    {filtered.length?<div className="problem-table-wrap"><table className="problem-table"><thead><tr><th scope="col">PROBLEM <ArrowDown size={12}/></th><th scope="col">TOPICS</th><th scope="col">LAST ATTEMPT</th><th scope="col">WHERE YOU LEFT OFF</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map(problem=>{const last=latestReflection(data,problem.id);return <tr key={problem.id}><td><button className="problem-title-button" onClick={()=>setSelected(problem)}>{problem.title}</button><div className="problem-meta"><span>{problem.platform}</span>{problem.cfHandle&&<span>{problem.cfHandle}</span>}{problem.platform==="Codeforces"&&!problem.cfHandle&&<span>Personal notebook</span>}{problem.problemCode && <span className="mono">#{problem.problemCode}</span>}{problem.rating!==null&&<span className="mono">{problem.rating}</span>}</div></td><td><Tags tags={problem.tags}/></td><td className="date-cell mono">{last?shortDate(last.completedAt):"—"}</td><td>{last?<OutcomeLabel outcome={last.outcome}/>:problem.cfHandle?<span className="reflection-state">Reflection pending</span>:<OutcomeLabel outcome={undefined}/>}</td><td><button className="icon-button start-row" aria-label={`Start session: ${problem.title}`} onClick={()=>startSession(problem)}><ArrowUpRight size={19}/></button></td></tr>;})}</tbody></table><div className="list-end"><span>{filtered.length} of {available.length} problems</span><span>Small steps add up.</span></div></div>:<EmptyState icon={<BookOpen size={28} strokeWidth={1.4}/>} title={available.length?"No problems on this page yet.":"Your notebook is an open page."} description={available.length?"Try a different search or loosen the filters a little.":"Bring a problem from Codeforces, LeetCode, or anywhere you like to practise."} action={available.length?<button className="button secondary" onClick={clear}>Clear filters</button>:<button className="button primary" onClick={()=>setAddOpen(true)}><Plus size={17}/>Add my first problem</button>}/>}
    {selected && <Modal title={selected.title} onClose={()=>setSelected(null)} className="history-modal"><div className="history-meta"><div className="problem-meta"><span>{selected.platform}</span><span className="mono">{selected.problemCode?`#${selected.problemCode}`:""}</span>{selected.rating!==null&&<span className="mono">{selected.rating} rating</span>}</div><button className="text-link" onClick={()=>{setEditing(selected);setSelected(null);}}><Pencil size={14}/>Edit details</button></div><Tags tags={selected.tags}/><div className="history-external"><ProblemLink problem={selected}/></div><div className="section-heading"><h3>Every attempt is part of the story.</h3></div>{selected.cfHandle&&<p className="small muted">Imported activity belongs to {selected.cfHandle}. <a href="/activity" className="text-link">View or edit its quick reflections</a>. Timed sessions are listed below.</p>}<div className="attempt-history">{data.attempts.filter(a=>a.problemId===selected.id).sort((a,b)=>b.completedAt.localeCompare(a.completedAt)).map(attempt=><article key={attempt.id} className="attempt-entry"><div><OutcomeLabel outcome={attempt.outcome}/><span className="mono tiny muted">{shortDate(attempt.completedAt)} · {Math.floor(attempt.elapsedMs/60000)} min</span></div>{attempt.difficulty&&<p className="small muted">Working on: {DIFFICULTIES[attempt.difficulty]}</p>}{attempt.takeaway&&<p className="takeaway">“{attempt.takeaway}”</p>}{attempt.notes&&<details><summary>Session notes</summary><p className="saved-notes">{attempt.notes}</p></details>}</article>)}{!data.attempts.some(a=>a.problemId===selected.id)&&<p className="muted">No attempts yet. Give it a little time and see where it takes you.</p>}</div><div className="form-actions"><button className="button primary" onClick={()=>{startSession(selected);setSelected(null);}}>Start a fresh attempt<ArrowRight size={16}/></button></div></Modal>}
    {editing && <AddProblem problem={editing} onClose={()=>setEditing(null)}/>}
  </div>;
}
